# Generated by Django 5.1.3 on 2024-11-20 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='profile_picture',
            new_name='profile_pic',
        ),
    ]
